# https://marketplace.visualstudio.com/items?itemName=humao.rest-client

### Default number
https://localhost:44303/api/numbers

### Named number
https://localhost:44303/api/numbers?key=PersonNumber

### Health checks
https://localhost:44303/health

### Deployed
### Health checks
https://appserviceconfig-aue.azurewebsites.net/health

### Numbers
https://appserviceconfig-aue.azurewebsites.net/api/numbers

### Configuration
https://appserviceconfig-aue.azurewebsites.net/api/configuration
