# https://marketplace.visualstudio.com/items?itemName=humao.rest-client

### Default number
https://localhost:44303/api/numbers

### Named number
https://localhost:44303/api/numbers?key=PersonNumber

### Health checks
https://localhost:44303/health
